version: '3.8'

services:
  drupal:
    container_name: drupal_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./drupal:/opt/drupal/
    networks:
      - drupal_net
    depends_on:
      - database

  database:
    container_name: drupal-db
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal_net

networks:
  drupal_net:
    driver: bridge

volumes:
  drupal:
  db-data:
